# Generated by Django 4.1.2 on 2022-10-18 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField(validators=[django.core.validators.MinValueValidator], verbose_name='ساعت شروع')),
                ('end_hour', models.IntegerField(verbose_name='ساعت پایان')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس ها',
            },
        ),
    ]
