# Generated by Django 4.1.2 on 2022-10-18 13:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=50, verbose_name='بازی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('opinion', models.TextField(verbose_name='نظر')),
                ('rate', models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)], verbose_name='رتبه')),
                ('accepted', models.BooleanField(default=False, verbose_name='وضعیت تایید شدن')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان')),
            ],
            options={
                'verbose_name': 'نظر بازی',
                'verbose_name_plural': 'نظرات بازی ها',
            },
        ),
    ]
